### ISSUE TITLE
How can I use this package for nextjs 13

### ISSUE THREAD

**Issue by woohelps** [btk/nextjs-google-adsense#35]
I try to use this package on my new nextjs 13, but it looks like doesn't work, would you please give me the instruction that how to use it on nextjs 13 project?

**Comment by awitherow** [comment]
@woohelps i added it to my layout.tsx and have not had my account approved yet to test.

How did you add yours?

**Comment by btk** [comment]
Yes currently using it on a next 13 project myself, no issue, feel free to open a new issue if you face any
